#[derive(Debug)]
pub enum MerchantCity {
    Battambang,
    BanteayMeanChey,
    KampongCham,
    KampongChhnang,
    KampongSpeu,
    KampongThom,
    Kandal,
    Kep,
    KohKong,
    Kratie,
    Mondolkiri,
    OddorMeanchey,
    Pailin,
    PoiPet,
    PhnomPenh,
    PreahVihear,
    PreyVeng,
    Pursat,
    Ratanakiri,
    SiemReap,
    SihanoukVille,
    SteungTreng,
    SvayRieng,
    Takeo,
    TboungKhmum,
}

impl MerchantCity {
    pub fn from_string(s: &str) -> Option<Self> {
        match s {
            "Battambang" => Some(Self::Battambang),
            "BMC" => Some(Self::BanteayMeanChey),
            "Kampong Cham" => Some(Self::KampongCham),
            "Kampong Chhnang" => Some(Self::KampongChhnang),
            "Kampong Speu" => Some(Self::KampongSpeu),
            "Kampong Thom" => Some(Self::KampongThom),
            "Kandal" => Some(Self::Kandal),
            "Kep" => Some(Self::Kep),
            "Koh Kong" => Some(Self::KohKong),
            "Kratie" => Some(Self::Kratie),
            "Mondolkiri" => Some(Self::Mondolkiri),
            "Oddor Meanchey" => Some(Self::OddorMeanchey),
            "Pailin" => Some(Self::Pailin),
            "Pady Paet" => Some(Self::PoiPet),
            "Phnom Penh" => Some(Self::PhnomPenh),
            "Preah Vihear" => Some(Self::PreahVihear),
            "Prey Veng" => Some(Self::PreyVeng),
            "Pursat" => Some(Self::Pursat),
            "Ratanakiri" => Some(Self::Ratanakiri),
            "Siem Reap" => Some(Self::SiemReap),
            "Sihanouk Ville" => Some(Self::SihanoukVille),
            "Steung Treng" => Some(Self::SteungTreng),
            "Svay Rieng" => Some(Self::SvayRieng),
            "Takeo" => Some(Self::Takeo),
            "Tboung Khmum" => Some(Self::TboungKhmum),
            _ => None,
        }
    }

    pub fn city(&self) -> &'static str {
        match self {
            Self::Battambang => "Battambang",
            Self::BanteayMeanChey => "BMC",
            Self::KampongCham => "Kampong Cham",
            Self::KampongChhnang => "Kampong Chhnang",
            Self::KampongSpeu => "Kampong Speu",
            Self::KampongThom => "Kampong Thom",
            Self::Kandal => "Kandal",
            Self::Kep => "Kep",
            Self::KohKong => "Koh Kong",
            Self::Kratie => "Kratie",
            Self::Mondolkiri => "Mondolkiri",
            Self::OddorMeanchey => "Oddor Meanchey",
            Self::Pailin => "Pailin",
            Self::PoiPet => "Pady Paet",
            Self::PhnomPenh => "Phnom Penh",
            Self::PreahVihear => "Preah Vihear",
            Self::PreyVeng => "Prey Veng",
            Self::Pursat => "Pursat",
            Self::Ratanakiri => "Ratanakiri",
            Self::SiemReap => "Siem Reap",
            Self::SihanoukVille => "Sihanouk Ville",
            Self::SteungTreng => "Steung Treng",
            Self::SvayRieng => "Svay Rieng",
            Self::Takeo => "Takeo",
            Self::TboungKhmum => "Tboung Khmum",
        }
    }
}
